"""Add network usage data to Device model and create NetworkUsage model

Revision ID: 6555ae3594b4
Revises: 727732e543bc
Create Date: 2024-10-31 17:53:06.786961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6555ae3594b4'
down_revision = '727732e543bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bandwidth_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('bandwidth_limit')

    # ### end Alembic commands ###
