"""Add network usage data to Device model and create NetworkUsage model

Revision ID: 727732e543bc
Revises: af3eca74c50b
Create Date: 2024-10-21 15:09:03.142912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '727732e543bc'
down_revision = 'af3eca74c50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index('ix_device_ip_address')
        batch_op.drop_index('ix_device_mac_address')

    op.drop_table('device')
    op.drop_table('user')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_usage', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('last_usage_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_usage_update')
        batch_op.drop_column('data_usage')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('device',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='device_pkey')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index('ix_device_mac_address', ['mac_address'], unique=True)
        batch_op.create_index('ix_device_ip_address', ['ip_address'], unique=False)

    # ### end Alembic commands ###
