"""Add last_seen column to Device model

Revision ID: af3eca74c50b
Revises: 
Create Date: 2024-10-20 10:22:17.324868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3eca74c50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_device_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_mac_address'), ['mac_address'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_mac_address'))
        batch_op.drop_index(batch_op.f('ix_device_ip_address'))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
